spring:
  datasource:
    url: jdbc:mysql://127.0.0.0:3306/Test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: beyondys
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    maxActive: 20
    minIdle: 8
    initialSize: 5

  rabbitmq:
    addresses: 127.0.0.0
    port: 5672

  redis:
    port: 6379
    host: 127.0.0.0
    password: beyondys

  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.0:9300
      repositories:
        enabled: true


mybatis:
  configuration:
    map-underscore-to-camel-case: true

#debug: true
