spring:
  datasource:
    url: jdbc:mysql://47.104.203.206:3306/Test
    username: root
    password: beyondys
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    maxActive: 20
    minIdle: 8
    initialSize: 5

  rabbitmq:
    addresses: 47.104.203.206
    port: 5672

  redis:
    port: 6379
    host: 47.104.203.206
    password: beyondys

mybatis:
  configuration:
    map-underscore-to-camel-case: true

debug: true
