spring:
  datasource:
    url: jdbc:mysql://39.105.60.201:3306/Test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ys201015
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    maxActive: 20
    minIdle: 8
    initialSize: 5

  rabbitmq:
    addresses: 39.105.60.201
    port: 5672

  redis:
    port: 6379
    host: 39.105.60.201
    password: ys201015

  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 39.105.60.201:9300
      repositories:
        enabled: true


mybatis:
  configuration:
    map-underscore-to-camel-case: true

#debug: true
