package com.eason.demo.springbootmqredis.po;

import org.springframework.data.elasticsearch.annotations.Document;

import java.io.Serializable;

@Document(indexName = "hotel",type = "KF")
public class Kf implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.﻿u_Name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.CardNo
     *
     * @mbggenerated
     */
    private String cardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.Descriot
     *
     * @mbggenerated
     */
    private String descriot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.CtfTp
     *
     * @mbggenerated
     */
    private String ctftp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.CtfId
     *
     * @mbggenerated
     */
    private String ctfid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.Gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.Birthday
     *
     * @mbggenerated
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.Address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.Zip
     *
     * @mbggenerated
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.Dirty
     *
     * @mbggenerated
     */
    private String dirty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.District1
     *
     * @mbggenerated
     */
    private String district1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.District2
     *
     * @mbggenerated
     */
    private String district2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.District3
     *
     * @mbggenerated
     */
    private String district3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.District4
     *
     * @mbggenerated
     */
    private String district4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.District5
     *
     * @mbggenerated
     */
    private String district5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.District6
     *
     * @mbggenerated
     */
    private String district6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.FirstNm
     *
     * @mbggenerated
     */
    private String firstnm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.LastNm
     *
     * @mbggenerated
     */
    private String lastnm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.Duty
     *
     * @mbggenerated
     */
    private String duty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.Mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.Tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.Fax
     *
     * @mbggenerated
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.EMail
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.Nation
     *
     * @mbggenerated
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.Taste
     *
     * @mbggenerated
     */
    private String taste;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.Education
     *
     * @mbggenerated
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.Company
     *
     * @mbggenerated
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.CTel
     *
     * @mbggenerated
     */
    private String ctel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.CAddress
     *
     * @mbggenerated
     */
    private String caddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.CZip
     *
     * @mbggenerated
     */
    private String czip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.Family
     *
     * @mbggenerated
     */
    private String family;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.Version
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kf.id
     *
     * @mbggenerated
     */
    private String id;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.CardNo
     *
     * @return the value of kf.CardNo
     *
     * @mbggenerated
     */
    public String getCardno() {
        return cardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.CardNo
     *
     * @param cardno the value for kf.CardNo
     *
     * @mbggenerated
     */
    public void setCardno(String cardno) {
        this.cardno = cardno == null ? null : cardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.Descriot
     *
     * @return the value of kf.Descriot
     *
     * @mbggenerated
     */
    public String getDescriot() {
        return descriot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.Descriot
     *
     * @param descriot the value for kf.Descriot
     *
     * @mbggenerated
     */
    public void setDescriot(String descriot) {
        this.descriot = descriot == null ? null : descriot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.CtfTp
     *
     * @return the value of kf.CtfTp
     *
     * @mbggenerated
     */
    public String getCtftp() {
        return ctftp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.CtfTp
     *
     * @param ctftp the value for kf.CtfTp
     *
     * @mbggenerated
     */
    public void setCtftp(String ctftp) {
        this.ctftp = ctftp == null ? null : ctftp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.CtfId
     *
     * @return the value of kf.CtfId
     *
     * @mbggenerated
     */
    public String getCtfid() {
        return ctfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.CtfId
     *
     * @param ctfid the value for kf.CtfId
     *
     * @mbggenerated
     */
    public void setCtfid(String ctfid) {
        this.ctfid = ctfid == null ? null : ctfid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.Gender
     *
     * @return the value of kf.Gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.Gender
     *
     * @param gender the value for kf.Gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.Birthday
     *
     * @return the value of kf.Birthday
     *
     * @mbggenerated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.Birthday
     *
     * @param birthday the value for kf.Birthday
     *
     * @mbggenerated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.Address
     *
     * @return the value of kf.Address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.Address
     *
     * @param address the value for kf.Address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.Zip
     *
     * @return the value of kf.Zip
     *
     * @mbggenerated
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.Zip
     *
     * @param zip the value for kf.Zip
     *
     * @mbggenerated
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.Dirty
     *
     * @return the value of kf.Dirty
     *
     * @mbggenerated
     */
    public String getDirty() {
        return dirty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.Dirty
     *
     * @param dirty the value for kf.Dirty
     *
     * @mbggenerated
     */
    public void setDirty(String dirty) {
        this.dirty = dirty == null ? null : dirty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.District1
     *
     * @return the value of kf.District1
     *
     * @mbggenerated
     */
    public String getDistrict1() {
        return district1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.District1
     *
     * @param district1 the value for kf.District1
     *
     * @mbggenerated
     */
    public void setDistrict1(String district1) {
        this.district1 = district1 == null ? null : district1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.District2
     *
     * @return the value of kf.District2
     *
     * @mbggenerated
     */
    public String getDistrict2() {
        return district2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.District2
     *
     * @param district2 the value for kf.District2
     *
     * @mbggenerated
     */
    public void setDistrict2(String district2) {
        this.district2 = district2 == null ? null : district2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.District3
     *
     * @return the value of kf.District3
     *
     * @mbggenerated
     */
    public String getDistrict3() {
        return district3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.District3
     *
     * @param district3 the value for kf.District3
     *
     * @mbggenerated
     */
    public void setDistrict3(String district3) {
        this.district3 = district3 == null ? null : district3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.District4
     *
     * @return the value of kf.District4
     *
     * @mbggenerated
     */
    public String getDistrict4() {
        return district4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.District4
     *
     * @param district4 the value for kf.District4
     *
     * @mbggenerated
     */
    public void setDistrict4(String district4) {
        this.district4 = district4 == null ? null : district4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.District5
     *
     * @return the value of kf.District5
     *
     * @mbggenerated
     */
    public String getDistrict5() {
        return district5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.District5
     *
     * @param district5 the value for kf.District5
     *
     * @mbggenerated
     */
    public void setDistrict5(String district5) {
        this.district5 = district5 == null ? null : district5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.District6
     *
     * @return the value of kf.District6
     *
     * @mbggenerated
     */
    public String getDistrict6() {
        return district6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.District6
     *
     * @param district6 the value for kf.District6
     *
     * @mbggenerated
     */
    public void setDistrict6(String district6) {
        this.district6 = district6 == null ? null : district6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.FirstNm
     *
     * @return the value of kf.FirstNm
     *
     * @mbggenerated
     */
    public String getFirstnm() {
        return firstnm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.FirstNm
     *
     * @param firstnm the value for kf.FirstNm
     *
     * @mbggenerated
     */
    public void setFirstnm(String firstnm) {
        this.firstnm = firstnm == null ? null : firstnm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.LastNm
     *
     * @return the value of kf.LastNm
     *
     * @mbggenerated
     */
    public String getLastnm() {
        return lastnm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.LastNm
     *
     * @param lastnm the value for kf.LastNm
     *
     * @mbggenerated
     */
    public void setLastnm(String lastnm) {
        this.lastnm = lastnm == null ? null : lastnm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.Duty
     *
     * @return the value of kf.Duty
     *
     * @mbggenerated
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.Duty
     *
     * @param duty the value for kf.Duty
     *
     * @mbggenerated
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.Mobile
     *
     * @return the value of kf.Mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.Mobile
     *
     * @param mobile the value for kf.Mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.Tel
     *
     * @return the value of kf.Tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.Tel
     *
     * @param tel the value for kf.Tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.Fax
     *
     * @return the value of kf.Fax
     *
     * @mbggenerated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.Fax
     *
     * @param fax the value for kf.Fax
     *
     * @mbggenerated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.EMail
     *
     * @return the value of kf.EMail
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.EMail
     *
     * @param email the value for kf.EMail
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.Nation
     *
     * @return the value of kf.Nation
     *
     * @mbggenerated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.Nation
     *
     * @param nation the value for kf.Nation
     *
     * @mbggenerated
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.Taste
     *
     * @return the value of kf.Taste
     *
     * @mbggenerated
     */
    public String getTaste() {
        return taste;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.Taste
     *
     * @param taste the value for kf.Taste
     *
     * @mbggenerated
     */
    public void setTaste(String taste) {
        this.taste = taste == null ? null : taste.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.Education
     *
     * @return the value of kf.Education
     *
     * @mbggenerated
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.Education
     *
     * @param education the value for kf.Education
     *
     * @mbggenerated
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.Company
     *
     * @return the value of kf.Company
     *
     * @mbggenerated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.Company
     *
     * @param company the value for kf.Company
     *
     * @mbggenerated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.CTel
     *
     * @return the value of kf.CTel
     *
     * @mbggenerated
     */
    public String getCtel() {
        return ctel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.CTel
     *
     * @param ctel the value for kf.CTel
     *
     * @mbggenerated
     */
    public void setCtel(String ctel) {
        this.ctel = ctel == null ? null : ctel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.CAddress
     *
     * @return the value of kf.CAddress
     *
     * @mbggenerated
     */
    public String getCaddress() {
        return caddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.CAddress
     *
     * @param caddress the value for kf.CAddress
     *
     * @mbggenerated
     */
    public void setCaddress(String caddress) {
        this.caddress = caddress == null ? null : caddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.CZip
     *
     * @return the value of kf.CZip
     *
     * @mbggenerated
     */
    public String getCzip() {
        return czip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.CZip
     *
     * @param czip the value for kf.CZip
     *
     * @mbggenerated
     */
    public void setCzip(String czip) {
        this.czip = czip == null ? null : czip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.Family
     *
     * @return the value of kf.Family
     *
     * @mbggenerated
     */
    public String getFamily() {
        return family;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.Family
     *
     * @param family the value for kf.Family
     *
     * @mbggenerated
     */
    public void setFamily(String family) {
        this.family = family == null ? null : family.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.Version
     *
     * @return the value of kf.Version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.Version
     *
     * @param version the value for kf.Version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kf.id
     *
     * @return the value of kf.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kf.id
     *
     * @param id the value for kf.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    @Override
    public String toString() {
        return "Kf{" +
                "cardno='" + cardno + '\'' +
                ", descriot='" + descriot + '\'' +
                ", ctftp='" + ctftp + '\'' +
                ", ctfid='" + ctfid + '\'' +
                ", gender='" + gender + '\'' +
                ", birthday='" + birthday + '\'' +
                ", address='" + address + '\'' +
                ", zip='" + zip + '\'' +
                ", dirty='" + dirty + '\'' +
                ", district1='" + district1 + '\'' +
                ", district2='" + district2 + '\'' +
                ", district3='" + district3 + '\'' +
                ", district4='" + district4 + '\'' +
                ", district5='" + district5 + '\'' +
                ", district6='" + district6 + '\'' +
                ", firstnm='" + firstnm + '\'' +
                ", lastnm='" + lastnm + '\'' +
                ", duty='" + duty + '\'' +
                ", mobile='" + mobile + '\'' +
                ", tel='" + tel + '\'' +
                ", fax='" + fax + '\'' +
                ", email='" + email + '\'' +
                ", nation='" + nation + '\'' +
                ", taste='" + taste + '\'' +
                ", education='" + education + '\'' +
                ", company='" + company + '\'' +
                ", ctel='" + ctel + '\'' +
                ", caddress='" + caddress + '\'' +
                ", czip='" + czip + '\'' +
                ", family='" + family + '\'' +
                ", version='" + version + '\'' +
                ", id='" + id + '\'' +
                '}';
    }
}